#!/usr/bin/env bash
# neonburro-shop · clear the old ground
# SENTINEL: NB_SHOP_CLEAN_V1
#
# Run from the repo root:  bash clean.sh
#
# Everything below is either regenerated by the build or already superseded.
# Nothing here is a source file and nothing here is in git except migrate-images.sh.

set -euo pipefail
cd "$(dirname "$0")"

echo "before:"
du -sh dist node_modules _to_delete 2>/dev/null || true
echo

# STALE BUILD OUTPUT. This is the folder that still shows images/products/t-shirts,
# images/profiles and images/scenes. It is a build from before any of this work,
# it is gitignored so it never updates on its own, and `yarn build` recreates it.
# It is the single most likely reason somebody thinks the new images are missing.
rm -rf dist

# The migration is done and it is in git history if it is ever needed again.
rm -f migrate-images.sh

# Unreferenced. index.html points og:image at shop-hero-sms.png.
rm -f public/og-image.png

# A folder containing one README about sounds that do not exist.
rm -rf public/sounds

echo "after:"
du -sh node_modules _to_delete 2>/dev/null || true
echo
echo "Still on disk, on purpose:"
echo "  _to_delete/originals-png    the full resolution PNG masters, 76MB"
echo "  _to_delete/public-legacy    the swept hero art"
echo "  _to_delete/sed-bak          backups from the path rewrites"
echo
echo "None of that is in git. Delete it yourself once you are happy:"
echo "  rm -rf _to_delete"
