functionsDirectory = "/Users/tyler/neonburro/netlify/functions"
functionsDirectoryOrigin = "ui"
redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/tyler/neonburro/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "yarn build"
functions = "/Users/tyler/neonburro/netlify/functions"

[build.environment]
NODE_VERSION = "18.18.0"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]